name: Arisatan
on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

jobs:
  arisatan:
    runs-on: ubuntu-latest
    steps:
      - name: Arisatan
        uses: Doarakko/action-lgtmoon@v1.0
        if: >-
          contains(github.event.comment.body, 'arisatan')
          || contains(github.event.review.body, 'arisatan')
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
